[{server,
  [{certfile, "/home/pradeeban/IGUANA/priv/ssl/cert.pem"},
   {keyfile, "/home/pradeeban/IGUANA/priv/ssl/key.pem"},
   {secure_renegotiate, true},
   {depth, 0},
   {verify, verify_peer},
   {fail_if_no_peer_cert, true},
   {cacertfile, "/home/pradeeban/IGUANA/priv/ssl/ca-cert.pem"}]},
 {client,
  [{certfile, "/home/pradeeban/IGUANA/priv/ssl/cert.pem"},
   {keyfile, "/home/pradeeban/IGUANA/priv/ssl/key.pem"},
   {secure_renegotiate, true},
   {depth, 0},
   {verify, verify_none},
   {cacertfile, "/home/pradeeban/IGUANA/priv/ssl/ca-cert.pem"}]}].
