name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:26.2

    steps:
    - uses: actions/checkout@v4
    - name: Compile Erlang Guardrail
      run: erlc src/iguana_entropy_guard.erl
    - name: Run Native Benchmark Suite
      run: |
        cd src/eval
        erlc benchmark.erl
        erl -noshell -s benchmark run -s init stop
